# Default values for cuda-gridder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# default to adding in chart tests
helmTests: true
testDataPath: "./"
gridder:
  enabled: true
  testData: "{{ .Values.testDataPath }}gridder_test_data"
  image:
    registry: localhost:5000
    image: cuda-gridder
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem
nodeSelector: {}

affinity: {}

tolerations: []
